package com.my.junit.testmanager.ui;

import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.my.junit.testmanager.utils.LoggerUtils;
import org.jetbrains.annotations.NotNull;

import javax.swing.*;

import java.awt.*;
import java.util.ArrayList;
import java.util.List;

import static com.my.junit.testmanager.utils.MessagesBundle.message;

/**
 * Абстрактная форма для добавления или редактирования с простыми Label и TextField полями.
 *
 * @param <T> Тип объекта, связанного с формой.
 */
public abstract class AbstractLabelForm<T> extends DialogWrapper {
    private JPanel table;
    private final LoggerUtils log = LoggerUtils.getLogger(AbstractLabelForm.class);
    private final String[] params;
    protected List<JTextField> textFields = new ArrayList<>();

    public AbstractLabelForm(@NotNull String... params) {
        super(true);
        setTitle(message("dialog.title.add"));
        this.params = params;
        init();
    }

    @Override
    protected JComponent createCenterPanel() {
        addLabelsAndTextFields();
        log.logInfo("Creating center panel for AbstractLabelForm");
        return this.table;
    }

    /**
     * Инициализация формы.
     */
    private void addLabelsAndTextFields() {
        final var layout = new GridBagLayout();
        this.table.setLayout(layout);

        final var gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;

        gbc.insets = new Insets(5, 5, 5, 5);
        for (int i = 0; i < this.params.length; i++) {
            final var label = new JLabel(this.params[i]);
            final var textField = new JTextField(20);

            gbc.gridx = 0;
            gbc.gridy = i;
            this.table.add(label, gbc);

            gbc.gridx = 1;
            this.table.add(textField, gbc);

            textFields.add(textField);
        }
    }

    /**
     * Получить объект, связанный с формой.
     *
     * @return Объект типа T.
     */
    protected abstract T getObject();

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        table = new JPanel();
        table.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {return table;}
}
