package com.my.junit.testmanager.ui;

import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.my.junit.testmanager.config.data.ProfileData;
import com.my.junit.testmanager.utils.LoggerUtils;
import org.jetbrains.annotations.Nullable;

import javax.swing.*;

import java.awt.*;

import static com.my.junit.testmanager.utils.MessagesBundle.message;

/**
 * Диалоговое окно для добавления или редактирования профиля.
 */
public class ProfileForm extends DialogWrapper {
    private JPanel table;
    private JLabel labelName;
    private JTextField nameField;
    private final ProfileData existingGroup;
    private final LoggerUtils log = LoggerUtils.getLogger(ProfileForm.class);

    public ProfileForm(@Nullable ProfileData existing) {
        super(true);
        this.existingGroup = existing;
        setTitle(existing == null ? message("dialog.title.add") : message("dialog.title.edit"));
        init();
    }

    @Override
    protected JComponent createCenterPanel() {
        this.labelName.setText(message("settings.label.profile.name"));
        this.labelName.setToolTipText(message("settings.label.profile.name.tooltip"));

        if (this.existingGroup != null) {
            log.logInfo("Editing existing profile: " + this.existingGroup);
            this.nameField.setText(existingGroup.getName());
        }
        return this.table;
    }

    public ProfileData getProfileConfigData() {
        return ProfileData.of(
                this.nameField.getText()
        );
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        table = new JPanel();
        table.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        labelName = new JLabel();
        labelName.setText("Наименование");
        table.add(labelName, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nameField = new JTextField();
        table.add(nameField,
                new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                        GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                        new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {return table;}
}
